#!/usr/bin/env ruby

# Runtime to ffmpeg timecode calculator because my brain don't work good hung over :(

mins = ARGV[0].to_i
unless ARGV[1].nil?
	mins += ARGV[1].to_i # + time buffer for lead in
end

puts "#{(mins/60).floor.to_s.rjust(2,"0")}:#{(mins%60).to_s.rjust(2,"0")}:00.00"