#!/bin/bash

# ffmpeg -f avfoundation -video_device_index 1 -audio_device_index 1 -framerate 60 -video_size 640x480 -i "default" -vf "scale=720:576" -vcodec libx264 -tune zerolatency -b 900k -f mpegts udp://192.168.0.3:6666
ffmpeg -f avfoundation -video_device_index 0 -audio_device_index 2 -framerate 60 -video_size 640x480 -i "default" -tune zerolatency -vb 1024k -vcodec libx264 -r 25 -acodec libvo_aacenc -ab 128k -b:v 256k -buffer_size 6M -bufsize 8M -minrate 1.5M -maxrate 2M -f mpegts udp://192.168.0.3:6666

